"""Simulate PacBio long reads from a reference genome.

Wraps the PBSIM3 (pbsim) tool to generate realistic PacBio
continuous long reads (CLR) or HiFi circular consensus reads.
"""

import logging
from pathlib import Path

from simulate_data.longread import resolve_model_path, run_ccs
from simulate_data.utils import (
    check_tool_installed,
    ensure_output_dir,
    run_command,
    validate_fasta,
)

logger = logging.getLogger(__name__)

# PBSIM3's documented values. Its built-in default of 6:55:39 is RS II.
RSII_DIFFERENCE_RATIO = "6:55:39"
SEQUEL_DIFFERENCE_RATIO = "22:45:33"
# HiFi is generated by collapsing multi-pass subreads with ccs, which needs
# an error model rather than a quality-score model.
HIFI_ERROR_MODEL = "ERRHMM-SEQUEL"


def register_parser(parser):
    """Define the reads-pacbio subcommand's CLI arguments."""
    parser.add_argument(
        "--ref",
        required=True,
        help="Reference genome FASTA",
    )
    parser.add_argument(
        "--coverage",
        type=float,
        default=20.0,
        help="Coverage depth (default: 20)",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output directory for FASTQ/BAM files",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for reproducibility",
    )
    parser.add_argument(
        "--read-type",
        choices=["CLR", "HiFi"],
        default="CLR",
        help="Read type: CLR or HiFi (default: CLR)",
    )
    parser.add_argument(
        "--read-length",
        type=int,
        default=15000,
        help="Mean read length in bp (default: 15000)",
    )
    parser.add_argument(
        "--read-std",
        type=int,
        default=13000,
        help="Read length standard deviation (default: 13000)",
    )
    parser.add_argument(
        "--pass-num",
        type=int,
        default=10,
        help="Number of passes for HiFi (default: 10)",
    )
    parser.add_argument(
        "--error-model",
        default="QSHMM-RSII",
        help="PBSIM3 error model (default: QSHMM-RSII)",
    )
    parser.add_argument(
        "--qscore-model",
        default=None,
        help="PBSIM3 quality score model",
    )
    parser.add_argument(
        "--difference-ratio",
        default=None,
        help=(
            "substitution:insertion:deletion ratio (default: "
            f"{SEQUEL_DIFFERENCE_RATIO} for HiFi, {RSII_DIFFERENCE_RATIO} for CLR)"
        ),
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=1,
        help="Threads for ccs consensus generation (default: 1)",
    )
    parser.add_argument(
        "--min-ccs-yield",
        type=float,
        default=0.5,
        help=(
            "Fail if the ccs ZMW yield falls below this fraction (default: 0.5). "
            "Low yield silently under-covers the genome."
        ),
    )


def _build_pbsim3_pacbio_command(
    ref_fasta: Path,
    coverage: float,
    output_prefix: str,
    read_type: str = "CLR",
    read_length: int = 15000,
    read_std: int = 13000,
    pass_num: int = 10,
    seed: int | None = None,
    error_model: str = "QSHMM-RSII",
    qscore_model: str | None = None,
    difference_ratio: str | None = None,
) -> list[str]:
    """Build the PBSIM3 (pbsim) command for PacBio read simulation.

    ``error_model`` may be a model name or a path; PBSIM3 requires a path to
    a .model file and fails with 'Cannot open file' on a bare name. HiFi
    switches to the errhmm method because ccs consumes multi-pass subreads.
    """
    method = "errhmm" if read_type == "HiFi" else "qshmm"
    model = HIFI_ERROR_MODEL if read_type == "HiFi" else error_model
    if difference_ratio is None:
        difference_ratio = (
            SEQUEL_DIFFERENCE_RATIO if read_type == "HiFi" else RSII_DIFFERENCE_RATIO
        )
    cmd = [
        "pbsim",
        "--strategy",
        "wgs",
        "--method",
        method,
        f"--{method}",
        str(resolve_model_path(model)),
        "--difference-ratio",
        difference_ratio,
        "--depth",
        str(coverage),
        "--length-mean",
        str(read_length),
        "--length-sd",
        str(read_std),
        "--genome",
        str(ref_fasta),
        "--prefix",
        output_prefix,
    ]

    if read_type == "HiFi":
        cmd.extend(["--pass-num", str(pass_num)])

    if qscore_model is not None:
        cmd.extend(["--qscore-model", qscore_model])

    if seed is not None:
        cmd.extend(["--seed", str(seed)])

    return cmd


def _validate_hifi(pass_num: int) -> None:
    """HiFi consensus requires multiple sequencing passes."""
    if pass_num <= 1:
        raise ValueError(
            f"--pass-num must be greater than 1 for HiFi, got {pass_num}; "
            "ccs derives a consensus from multiple passes"
        )


def main(args):
    """Simulate PacBio reads from a reference genome using PBSIM3."""
    # Validate inputs
    ref_path = Path(args.ref)
    validate_fasta(ref_path)

    if args.coverage <= 0:
        raise ValueError(f"--coverage must be positive, got {args.coverage}")

    if args.read_length <= 0:
        raise ValueError(f"--read-length must be positive, got {args.read_length}")

    if args.read_std < 0:
        raise ValueError(f"--read-std must be non-negative, got {args.read_std}")

    if args.read_type == "HiFi":
        _validate_hifi(args.pass_num)

    # Check tool installation
    check_tool_installed("pbsim")

    # Create output directory
    output_dir = ensure_output_dir(Path(args.output))

    # Build and run PBSIM3 command
    output_prefix = str(output_dir / "pacbio_reads")
    cmd = _build_pbsim3_pacbio_command(
        ref_fasta=ref_path,
        coverage=args.coverage,
        output_prefix=output_prefix,
        read_type=args.read_type,
        read_length=args.read_length,
        read_std=args.read_std,
        pass_num=args.pass_num,
        seed=args.seed,
        error_model=args.error_model,
        qscore_model=args.qscore_model,
        difference_ratio=args.difference_ratio,
    )

    logger.info("Simulating PacBio %s reads with PBSIM3", args.read_type)
    run_command(cmd)

    if args.read_type == "HiFi":
        # Multi-pass PBSIM3 emits subread BAMs, which are not usable reads
        # until ccs collapses them into consensus HiFi reads.
        subread_bams = sorted(output_dir.glob("pacbio_reads_*.bam"))
        if not subread_bams:
            raise RuntimeError(
                f"PBSIM3 produced no subread BAM for HiFi in {output_dir}"
            )
        for bam in subread_bams:
            hifi_fastq = bam.with_suffix(".fastq.gz")
            stats = run_ccs(
                bam,
                hifi_fastq,
                threads=args.threads,
                min_yield=args.min_ccs_yield,
            )
            logger.info(
                "ccs %s: %d/%d ZMWs (%.1f%% yield)",
                bam.name,
                stats["zmws_passed"],
                stats["zmws_input"],
                100 * stats["yield_fraction"],
            )
            bam.unlink()

    logger.info("PacBio read simulation complete. Output: %s", output_dir)
